# Generated by Django 2.2 on 2019-02-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
