# Generated by Django 2.2 on 2019-02-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_f_appApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
